// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id [your-project-id] > src/lib/supabase/types.ts

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          type: 'data_owner' | 'media_buyer' | 'both'
          properties: Record<string, any>
          settings: Record<string, any>
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['organizations']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>
      }
      users: {
        Row: {
          id: string
          email: string
          organization_id: string | null
          role: 'admin' | 'data_owner' | 'media_buyer' | 'analyst'
          properties: Record<string, any>
          settings: Record<string, any>
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      }
      data_assets: {
        Row: {
          id: string
          organization_id: string
          name: string
          asset_type: string
          status: string
          properties: Record<string, any>
          metadata: Record<string, any>
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['data_assets']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['data_assets']['Insert']>
      }
      campaigns: {
        Row: {
          id: string
          organization_id: string
          name: string
          status: string
          campaign_type: string
          properties: Record<string, any>
          settings: Record<string, any>
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['campaigns']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['campaigns']['Insert']>
      }
      events: {
        Row: {
          id: string
          event_type: string
          entity_type: string
          entity_id: string
          actor_id: string | null
          properties: Record<string, any>
          metadata: Record<string, any>
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['events']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['events']['Insert']>
      }
      metrics: {
        Row: {
          id: string
          metric_type: string
          entity_type: string
          entity_id: string
          value: number
          properties: Record<string, any>
          timestamp: string
        }
        Insert: Omit<Database['public']['Tables']['metrics']['Row'], 'id' | 'timestamp'>
        Update: Partial<Database['public']['Tables']['metrics']['Insert']>
      }
      relationships: {
        Row: {
          id: string
          relationship_type: string
          source_type: string
          source_id: string
          target_type: string
          target_id: string
          properties: Record<string, any>
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['relationships']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['relationships']['Insert']>
      }
      transactions: {
        Row: {
          id: string
          transaction_type: string
          from_entity_type: string | null
          from_entity_id: string | null
          to_entity_type: string | null
          to_entity_id: string | null
          amount: number
          currency: string
          properties: Record<string, any>
          status: string
          created_at: string
          processed_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['transactions']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['transactions']['Insert']>
      }
      permissions: {
        Row: {
          id: string
          resource_type: string
          resource_id: string | null
          actor_type: string
          actor_id: string
          permission: string
          conditions: Record<string, any>
          granted_at: string
          expires_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['permissions']['Row'], 'id' | 'granted_at'>
        Update: Partial<Database['public']['Tables']['permissions']['Insert']>
      }
    }
    Views: {
      campaign_performance: {
        Row: {
          id: string
          name: string
          organization_id: string
          properties: Record<string, any>
          impressions_30d: number
          revenue_30d: number
        }
      }
      data_asset_usage: {
        Row: {
          id: string
          name: string
          organization_id: string
          properties: Record<string, any>
          active_campaigns: number
          revenue_30d: number
        }
      }
    }
    Functions: {}
    Enums: {}
  }
}