export const mockDataAssets = [
  {
    id: "asset-1",
    name: "Premium Auto Intenders",
    type: "audience",
    status: "active",
    size: 2500000,
    qualityScore: 95,
    categories: ["automotive", "luxury"],
    pricePerUse: 0.05,
    activeCampaigns: 12,
    monthlyRevenue: 8420,
    totalQueries: 168400,
    refreshFrequency: "daily",
    description: "High-intent automotive buyers actively researching luxury vehicles"
  },
  {
    id: "asset-2",
    name: "Tech Early Adopters",
    type: "behavioral",
    status: "active",
    size: 1800000,
    qualityScore: 92,
    categories: ["technology", "innovation"],
    pricePerUse: 0.08,
    activeCampaigns: 18,
    monthlyRevenue: 12640,
    totalQueries: 158000,
    refreshFrequency: "weekly",
    description: "Users who consistently purchase new technology within 30 days of release"
  },
  {
    id: "asset-3",
    name: "High-Value E-commerce Shoppers",
    type: "transactional",
    status: "active",
    size: 3200000,
    qualityScore: 88,
    categories: ["retail", "e-commerce"],
    pricePerUse: 0.06,
    activeCampaigns: 24,
    monthlyRevenue: 15360,
    totalQueries: 256000,
    refreshFrequency: "real-time",
    description: "Shoppers with average order value >$200 across multiple categories"
  },
  {
    id: "asset-4",
    name: "Fitness & Wellness Enthusiasts",
    type: "interest",
    status: "active",
    size: 4100000,
    qualityScore: 90,
    categories: ["health", "fitness", "wellness"],
    pricePerUse: 0.04,
    activeCampaigns: 32,
    monthlyRevenue: 10240,
    totalQueries: 256000,
    refreshFrequency: "daily",
    description: "Active individuals engaged in fitness activities and wellness purchases"
  },
  {
    id: "asset-5",
    name: "Sustainable Living Advocates",
    type: "psychographic",
    status: "active",
    size: 1500000,
    qualityScore: 94,
    categories: ["sustainability", "eco-friendly"],
    pricePerUse: 0.07,
    activeCampaigns: 15,
    monthlyRevenue: 7350,
    totalQueries: 105000,
    refreshFrequency: "weekly",
    description: "Consumers prioritizing sustainable and eco-friendly products"
  },
  {
    id: "asset-6",
    name: "Travel Intent Signals",
    type: "intent",
    status: "active",
    size: 2800000,
    qualityScore: 91,
    categories: ["travel", "hospitality"],
    pricePerUse: 0.09,
    activeCampaigns: 20,
    monthlyRevenue: 14400,
    totalQueries: 160000,
    refreshFrequency: "real-time",
    description: "Users showing strong travel planning signals across multiple touchpoints"
  }
];